name: network_science
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - polars
  - pyarrow
  - numpy
  - scipy
  - python-igraph
  - leidenalg
  - matplotlib
  - seaborn
  - scikit-learn
  - gensim
  - pyyaml
  - pytest
  - tqdm
  - pip
  - pip:
    - cairocffi  # for igraph plotting on Windows
    - graspologic  # for SBM community detection
