name: network_science
channels:
  - conda-forge
dependencies:
  - python=3.11

  # Core data/science stack
  - numpy
  - scipy
  - pyarrow
  - polars

  # Graph stack
  - python-igraph
  - leidenalg
  - graspologic
  - graspologic-native

  # Plotting
  - matplotlib
  - seaborn

  # ML + NLP
  - scikit-learn
  - gensim

  # Utilities
  - pyyaml
  - tqdm
  - pytest

  # igraph Cairo bindings (Windows)
  - cairo
  - cairocffi
